chore: convert BigNumber to number after decoding
gelatodigital/automate-sdk pull request #42
Opened 2023-03-24 08:02 UTC by brandonchuah

2023-03-27 11:13 UTC, goums requested changes

2023-03-27 11:13 UTC, goums commented on src/lib/Web3Function/Web3FunctionSecrets.ts
let split this part in a distinct PR, as it is a breaking change, and we'll need a bit more thinking and work for this (UI changes, sdk, backend, ...)

2023-03-28 05:18 UTC, brandonchuah commented on src/lib/Web3Function/Web3FunctionSecrets.ts
[eff47f6](https://github.com/gelatodigital/automate-sdk/pull/42/commits/eff47f6324d2544fbaee19c11629910ce2d1882f)

2023-03-28 07:07 UTC, goums approved these changes

2023-03-28 07:07 UTC, merged